name: shop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  badges: ^3.1.1
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  flutter_animated_button: ^2.0.3
  rating_dialog: ^2.0.4
  bottom_sheet: ^3.1.2
  flutter_carousel_slider: ^1.1.0
  flutter_animated_dialog: ^2.0.1
  floating_snackbar: ^1.0.3+1
  selectable_container: ^1.0.7
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  path: ^1.8.3
  optimized_cached_image: ^3.0.1
  url_launcher: ^6.1.12
  fan_carousel_image_slider: ^0.1.2
  carousel_slider: ^4.2.1
  flutter_share: ^2.0.0
  multiple_images_picker: ^1.0.1
  firebase_app_check: ^0.1.5+1
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/shopping.png"
    min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/S0.png
      - assets/S1.png
      - assets/S2.png
      - assets/S3.png
      - assets/S4.png
      - assets/S5.png
      - assets/S6.png
      - assets/S7.jpg
      - assets/S8.jpeg
      - assets/Sp1.png
      - assets/Sp2.png
      - assets/Sp3.png
      - assets/profile.png
      - assets/city.gif
      - assets/signin.jpg
      - assets/signup.jpg
      - assets/paypal.png
      - assets/strip.png
      - assets/cod.png
      - assets/Icon/checklist.png
      - assets/Icon/communicate.png
      - assets/Icon/profile.png
      - assets/Icon/shutdown.png
      - assets/Icon/star.png
      - assets/group.png
      - assets/contact.png
      - assets/camera.png
      - assets/gallery.png
      - assets/whatsapp.png
      - assets/facebook.png
      - assets/sharing.png
      - assets/twitter.png
      - assets/sliderImages/sale.jpg
      - assets/sliderImages/shoe.jpg
      - assets/sliderImages/watch.jpg
      - assets/sliderImages/freedel.jpeg
      - assets/sliderImages/purse.jpg
      - assets/Ratings/ratingLogo.png
      - assets/shopping.png
  


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
